apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: apacha-hpa
spec:
  targetRef: # HPA replica target to our deployment, that's why we add apiVersion, kind, name of deployment here.
    apiVersion: apps/v1
    kind: Deployment
    name: apache-deployment
  updatePolicy:
    updateMode: "Auto"   #For Automatic Scaling
